### PR TITLE
Fix the problem about CORS Restriction

### PR DESCRIPTION
**Pull request by Panzer-Jack**
Fix the problem about CORS Restriction：
`MediaElementAudioSource outputs zeroes due to CORS access restrictions for http://127.0.0.1:5000/talk.wav`

Make it able to connect using URLs from different sources.

### CODE REVIEW

**Comment by RaSan147** [comment]
Approvedd thanks and sorry about the delay

**Comment by Panzer-Jack** [comment]
> Approvedd thanks and sorry about the delay

I see it was closed. If it means I need to pr again ?

**Comment by RaSan147** [comment]
wait what i didn't merge
sorryyy

**Comment by RaSan147** [comment]
done, accidentally closed instead of merge

**Pull request merged**
